package gitai

import (
	"fmt"
	"os"
	"path/filepath"
	"text/tabwriter"

	"github.com/BurntSushi/toml"
	"github.com/urfave/cli/v2"
)

// Config holds GitAI configuration
type Config struct {
	Model        string           `toml:"model"`
	ExchangeRate float64          `toml:"exchange_rate"`
	Currency     string           `toml:"default_currency"`
	Models       map[string]Model `toml:"models"`
	UserSettings map[string]string `toml:"user"`
}

// Model represents a custom model configuration
type Model struct {
	Name        string  `toml:"name"`
	Provider    string  `toml:"provider"`
	InputPrice  float64 `toml:"input_price"`
	OutputPrice float64 `toml:"output_price"`
	Currency    string  `toml:"currency"`
}

// GlobalConfig holds the loaded configuration
var GlobalConfig *Config

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	return &Config{
		Model:        "gpt-4o",
		ExchangeRate: 7.20,
		Currency:     "USD",
		Models: map[string]Model{
			"gpt-4o": {
				Name:        "gpt-4o",
				Provider:    "openai",
				InputPrice:  2.50,
				OutputPrice: 10.00,
				Currency:    "USD",
			},
			"gpt-4o-mini": {
				Name:        "gpt-4o-mini",
				Provider:    "openai",
				InputPrice:  0.15,
				OutputPrice: 0.60,
				Currency:    "USD",
			},
			"gpt-3.5-turbo": {
				Name:        "gpt-3.5-turbo",
				Provider:    "openai",
				InputPrice:  0.50,
				OutputPrice: 1.50,
				Currency:    "USD",
			},
			"qwen-plus": {
				Name:        "qwen-plus",
				Provider:    "alibaba",
				InputPrice:  0.50,
				OutputPrice: 2.00,
				Currency:    "CNY",
			},
			"qwen-turbo": {
				Name:        "qwen-turbo",
				Provider:    "alibaba",
				InputPrice:  0.08,
				OutputPrice: 0.30,
				Currency:    "CNY",
			},
			"wenxin-4.0": {
				Name:        "wenxin-4.0",
				Provider:    "baidu",
				InputPrice:  0.12,
				OutputPrice: 0.60,
				Currency:    "CNY",
			},
		},
		UserSettings: make(map[string]string),
	}
}

// LoadConfig loads configuration from .gitai/config.toml
func LoadConfig(root string) (*Config, error) {
	configPath := filepath.Join(root, GitaiDirName, ConfigFile)

	// If config doesn't exist, return default
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		cfg := DefaultConfig()
		GlobalConfig = cfg
		return cfg, nil
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read config: %w", err)
	}

	var config Config
	if err := toml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("failed to parse config: %w", err)
	}

	// Merge with defaults to ensure all required fields exist
	def := DefaultConfig()
	if config.Model == "" {
		config.Model = def.Model
	}
	if config.ExchangeRate == 0 {
		config.ExchangeRate = def.ExchangeRate
	}
	if config.Currency == "" {
		config.Currency = def.Currency
	}
	if config.Models == nil {
		config.Models = def.Models
	} else {
		// Merge models with defaults
		for name, model := range def.Models {
			if _, exists := config.Models[name]; !exists {
				config.Models[name] = model
			}
		}
	}
	if config.UserSettings == nil {
		config.UserSettings = def.UserSettings
	}

	GlobalConfig = &config
	return &config, nil
}

// MustLoadConfig loads config or exits
func MustLoadConfig(root string) *Config {
	cfg, err := LoadConfig(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading config: %v\n", err)
		os.Exit(1)
	}
	return cfg
}

// SaveConfig saves configuration to .gitai/config.toml
func SaveConfig(root string, config *Config) error {
	configPath := filepath.Join(root, GitaiDirName, ConfigFile)

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(configPath), 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	data, err := toml.Marshal(config)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	// Add header comment
	header := "# GitAI Configuration\n" +
		"# Generated by gitai. Do not edit manually unless you know what you're doing.\n\n"

	data = append([]byte(header), data...)

	if err := os.WriteFile(configPath, data, 0644); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	GlobalConfig = config
	return nil
}

// GetModelPricing gets pricing for a model from config
func (c *Config) GetModelPricing(modelName string) (*ModelPricing, error) {
	model, exists := c.Models[modelName]
	if !exists {
		return nil, fmt.Errorf("model not found: %s", modelName)
	}

	return &ModelPricing{
		Name:         model.Name,
		Provider:     model.Provider,
		InputPrice:   model.InputPrice,
		OutputPrice:  model.OutputPrice,
		Currency:     model.Currency,
		ExchangeRate: c.ExchangeRate,
	}, nil
}

// ConfigCmd handles configuration commands
func ConfigCmd(c *cli.Context) error {
	// Get git root
	_, root := MustGetGitRepo()

	// Check if .gitai/ is initialized
	storage := NewStorage(root)
	if !storage.IsInitialized() {
		return fmt.Errorf(".gitai/ not initialized. Run 'gitai init' first")
	}

	args := c.Args()

	if args.Len() == 0 {
		// Show current config
		return showConfig(root)
	}

	// Handle subcommands
	action := args.Get(0)
	switch action {
	case "set":
		return configSetCmd(c, root)
	case "get":
		return configGetCmd(c, root)
	case "list":
		return configListCmd(root)
	case "edit":
		return configEditCmd(root)
	case "init":
		return InitConfigCmd(c)
	default:
		return fmt.Errorf("unknown config action: %s\nUsage: gitai config [init|set|get|list|edit]", action)
	}
}

// showConfig displays current configuration
func showConfig(root string) error {
	config, err := LoadConfig(root)
	if err != nil {
		return err
	}

	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)

	fmt.Println("GitAI Configuration:")
	fmt.Println()

	fmt.Fprintf(w, "%s\t%s\n", "Setting", "Value")
	fmt.Fprintf(w, "%s\t%s\n", "-------", "-----")

	fmt.Fprintf(w, "%s\t%s\n", "model", config.Model)
	fmt.Fprintf(w, "%s\t%s\n", "default_currency", config.Currency)
	fmt.Fprintf(w, "%s\t%.2f\n", "exchange_rate", config.ExchangeRate)

	w.Flush()

	fmt.Printf("\nAvailable models: %d\n", len(config.Models))

	return nil
}

// configSetCmd sets a configuration value
func configSetCmd(c *cli.Context, root string) error {
	args := c.Args()

	if args.Len() < 2 {
		return fmt.Errorf("usage: gitai config set <key> <value>")
	}

	key := args.Get(1)
	value := args.Get(2)

	config, err := LoadConfig(root)
	if err != nil {
		return err
	}

	switch key {
	case "model":
		// Validate model exists
		if _, exists := config.Models[value]; !exists {
			return fmt.Errorf("unknown model: %s\nAvailable models: %v", value, getModelNames(config.Models))
		}
		config.Model = value
	case "currency", "default_currency":
		if value != "USD" && value != "CNY" {
			return fmt.Errorf("currency must be USD or CNY")
		}
		config.Currency = value
	case "exchange_rate":
		rate := 0.0
		_, err := fmt.Sscanf(value, "%f", &rate)
		if err != nil || rate <= 0 {
			return fmt.Errorf("invalid exchange rate: %s", value)
		}
		config.ExchangeRate = rate
	default:
		// Try to set as user setting
		config.UserSettings[key] = value
	}

	// Save config
	if err := SaveConfig(root, config); err != nil {
		return err
	}

	fmt.Printf("✓ Set %s = %s\n", key, value)
	return nil
}

// configGetCmd gets a configuration value
func configGetCmd(c *cli.Context, root string) error {
	args := c.Args()

	if args.Len() < 2 {
		return fmt.Errorf("usage: gitai config get <key>")
	}

	key := args.Get(1)

	config, err := LoadConfig(root)
	if err != nil {
		return err
	}

	switch key {
	case "model":
		fmt.Println(config.Model)
	case "currency", "default_currency":
		fmt.Println(config.Currency)
	case "exchange_rate":
		fmt.Printf("%.2f\n", config.ExchangeRate)
	default:
		// Check user settings
		if value, exists := config.UserSettings[key]; exists {
			fmt.Println(value)
		} else {
			return fmt.Errorf("unknown config key: %s", key)
		}
	}

	return nil
}

// configListCmd lists all available models
func configListCmd(root string) error {
	config, err := LoadConfig(root)
	if err != nil {
		return err
	}

	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)

	fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\n", "Model", "Provider", "Input", "Output", "Currency")
	fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\n", "-----", "--------", "-----", "------", "--------")

	for _, model := range config.Models {
		var inputPrice, outputPrice string
		if model.Currency == "USD" {
			inputPrice = fmt.Sprintf("$%.2f/M", model.InputPrice)
			outputPrice = fmt.Sprintf("$%.2f/M", model.OutputPrice)
		} else {
			inputPrice = fmt.Sprintf("¥%.2f/M", model.InputPrice)
			outputPrice = fmt.Sprintf("¥%.2f/M", model.OutputPrice)
		}

		marker := ""
		if model.Name == config.Model {
			marker = "*"
		}

		fmt.Fprintf(w, "%s%s\t%s\t%s\t%s\t%s\n",
			marker,
			model.Name,
			model.Provider,
			inputPrice,
			outputPrice,
			model.Currency,
		)
	}

	w.Flush()

	fmt.Printf("\n* = default model\n")
	fmt.Printf("Exchange rate: 1 USD = %.2f CNY\n", config.ExchangeRate)

	return nil
}

// configEditCmd opens config file in editor
func configEditCmd(root string) error {
	configPath := filepath.Join(root, GitaiDirName, ConfigFile)

	// Check if config exists, if not create default
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		config, _ := LoadConfig(root)
		if err := SaveConfig(root, config); err != nil {
			return err
		}
	}

	fmt.Printf("Config file location: %s\n", configPath)
	fmt.Println("Edit the file directly, then run 'gitai config list' to verify.")

	return nil
}

// InitConfigCmd initializes configuration file
func InitConfigCmd(c *cli.Context) error {
	// Get git root
	_, root := MustGetGitRepo()

	// Create default config
	config := DefaultConfig()

	// Save config
	if err := SaveConfig(root, config); err != nil {
		return err
	}

	fmt.Printf("✓ Created default configuration in .gitai/%s\n", ConfigFile)
	fmt.Printf("  View with: gitai config list\n")
	fmt.Printf("  Edit file: .gitai/%s\n", ConfigFile)

	return nil
}

// getModelNames returns list of available model names
func getModelNames(models map[string]Model) []string {
	names := make([]string, 0, len(models))
	for name := range models {
		names = append(names, name)
	}
	return names
}
